<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CandidateForm.aspx.cs" Inherits="WebApplication1.CandidateForm" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
   <head runat="server">
      <title></title>
   </head>
   <body>
      <form id="form1" runat="server">
         <div>
            <center>
               <h1>Candidate Details</h1>
               <asp:Table ID="Table1" runat="server" CssClass="align-content-center" Width="50%" BorderStyle ="Dotted">
                  <asp:TableRow>
                     <asp:TableCell>
                        <asp:Label ID="c_name" runat="server">Candidate Name</asp:Label>
                     </asp:TableCell>
                     <asp:TableCell>
                        <asp:TextBox ID="tb_cname" runat="server"></asp:TextBox>
                     </asp:TableCell>
                  </asp:TableRow>
                  <asp:TableRow>
                     <asp:TableCell>
                        <asp:Label ID="lb_dob" runat="server" Text="Date of Birth">Date of Birth</asp:Label>
                     </asp:TableCell>
                     <asp:TableCell>
                        <asp:TextBox ID="tb_dob" runat="server"  type="Date" AutoPostBack="true" OnTextChanged="TbDobTextChanged"></asp:TextBox>
                     </asp:TableCell>
                  </asp:TableRow>
                  <asp:TableRow>
                     <asp:TableCell>
                        <asp:Label ID="lb_age" runat="server" Text="Label">Age</asp:Label>
                     </asp:TableCell>
                     <asp:TableCell>
                        <asp:TextBox ID="tb_age" runat="server" Enabled="false" ></asp:TextBox>
                     </asp:TableCell>
                  </asp:TableRow>
                  <asp:TableRow>
                     <asp:TableCell>
                        <asp:Label ID="Label3" runat="server" Text="Label">City</asp:Label>
                     </asp:TableCell>
                     <asp:TableCell>
                        <asp:DropDownList ID="DropDownList1" runat="server"></asp:DropDownList>
                     </asp:TableCell>
                  </asp:TableRow>
                  <asp:TableRow>
                     <asp:TableCell>
                        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Save" CssClass="btn btn-danger" Font-Bold="true"/>
                     </asp:TableCell>
                     <asp:TableCell>
                        <asp:Button ID="Button2" OnClick="Button2_Click" runat="server" Text="Clear" CssClass="btn btn-close-white" Font-Bold="true"/>
                     </asp:TableCell>
                  </asp:TableRow>
                  <asp:TableRow>
                     <asp:TableCell>
                        
                         
                     </asp:TableCell>
                  </asp:TableRow>
               </asp:Table>
                <asp:GridView ID="GridView1" runat="server" HorizontalAlign="Center" DataKeyNames="Sr_No" OnRowEditing="GridView1_RowEditing" OnRowUpdating ="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="Gridview1_RowDeleting"  HeaderStyle-HorizontalAlign="Center" AutoGenerateDeleteButton="True" AutoGenerateColumns="False"  AutoGenerateEditButton="True">
   <Columns>
      <asp:TemplateField HeaderText="Sr_No">
         <ItemTemplate>
            <asp:Label ID="lbl_Sr_No" runat="server" Text='<%#Eval("Sr_No") %>'></asp:Label>
         </ItemTemplate>
      </asp:TemplateField>
      <asp:TemplateField HeaderText="Candidate_Name">
         <ItemTemplate>
            <asp:Label ID="lbl_Candidate_Name" runat="server" Text='<%#Eval("Candidate_Name") %>'></asp:Label>
         </ItemTemplate>
         <EditItemTemplate>
            <asp:TextBox ID="txt_Candidate_Name" runat="server" Text='<%#Eval("Candidate_Name") %>'></asp:TextBox>
         </EditItemTemplate>
      </asp:TemplateField>
      <asp:TemplateField HeaderText="DOB">
         <ItemTemplate>
            <asp:Label ID="lbl_DOB" runat="server" Text='<%#Eval("DOB") %>'></asp:Label>
         </ItemTemplate>
         <EditItemTemplate>
            <asp:TextBox ID="txt_DOB" runat="server" Text='<%#Eval("DOB") %>'></asp:TextBox>
         </EditItemTemplate>
      </asp:TemplateField>
      <asp:TemplateField HeaderText="Age">
         <ItemTemplate>
            <asp:Label ID="lbl_Age" runat="server" Text='<%#Eval("Age") %>'></asp:Label>
         </ItemTemplate>
         <EditItemTemplate>
            <asp:TextBox ID="txt_Age" runat="server" Text='<%#Eval("Age") %>'></asp:TextBox>
         </EditItemTemplate>
      </asp:TemplateField>
      <asp:TemplateField HeaderText="City">
         <ItemTemplate>
            <asp:Label ID="lbl_City" runat="server" Text='<%#Eval("City") %>'></asp:Label>
 
        </ItemTemplate>
         <EditItemTemplate>
             <asp:TextBox ID="txt_City" runat="server"></asp:TextBox>
              <%--<asp:DropDownList AutoPostBack="true" ID="ddlCities"  runat="server" DataTextField="city_name" DataValueField="city_id" OnDataBound="ddlCities_DataBound"> </asp:DropDownList>--%>
         </EditItemTemplate>
      </asp:TemplateField>
   </Columns>
   <HeaderStyle BackColor="#663300" ForeColor="#ffffff"/>
   <RowStyle BackColor="#e7ceb6"/>
</asp:GridView>
            </center>
         </div>
      </form>
   </body>
</html>